version: "3.7"

services:

    reverse-proxy:

        image: "jwilder/nginx-proxy:latest"

        container_name: "reverse-proxy"

        ports:
            - "80:80"
            - "443:443"

        volumes:
            - "certs:/etc/nginx/certs"
            - "vhost:/etc/nginx/vhost.d"
            - "html:/usr/share/nginx/html"
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - "./proxy.conf:/etc/nginx/conf.d/proxy.conf"

        environment:
            - VIRTUAL_PROTO=https
            - HTTPS_METHOD=redirect

        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

        restart: "always"

        networks:
            - "net"

    letsencrypt:
        image: "jrcs/letsencrypt-nginx-proxy-companion:latest"

        volumes:
            - "certs:/etc/nginx/certs"
            - "vhost:/etc/nginx/vhost.d"
            - "html:/usr/share/nginx/html"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            - DEFAULT_EMAIL
        depends_on:
            - "reverse-proxy"

        restart: "always"

volumes:
    certs:
    vhost:
    html:

networks:
    net:
        external: true
